export enum VideoFormat {
  MP4 = 'mp4',
  WEBM = 'webm',
  FLV = 'flv',
  AVI = 'avi',
  MOV = 'mov',
  WMV = 'wmv',
  GP3 = '3gp',
  MKV = 'mkv',
  M4V = 'm4v',
  MPG = 'mpg',
  MPEG = 'mpeg',
  VOB = 'vob',
  TS = 'ts',
  ASF = 'asf',
  F4V = 'f4v',
  H264 = 'h264',
  HEVC = 'hevc',
  M2TS = 'm2ts',
  M2V = 'm2v',
  MTS = 'mts',
  OGV = 'ogv',
  RM = 'rm',
  SWF = 'swf',
  XVID = 'xvid',
}
